use std::error::Error;
use std::fmt;
use std::fs;
use std::path::Path;

use serde::Deserialize;
use sessionscope_reporters::ReportFormat;

use crate::enforcement::{parse_category, parse_severity};

pub const CONFIG_FILE_NAME: &str = "sessionscope.toml";

pub const DEFAULT_CONFIG: &str = concat!(
    "# SessionScope configuration\n",
    "# Generated by `sessionscope init`. Safe to check in.\n",
    "# Do not put token values, private keys, bearer strings, cookie values, or\n",
    "# environment-specific secrets in this file.\n",
    "\n",
    "# Scan roots are repository-relative. v0.1.0 uses the first path.\n",
    "scan_paths = [\".\"]\n",
    "\n",
    "# Include patterns form the allowlist for source/config discovery.\n",
    "include = [\"**/*.js\", \"**/*.jsx\", \"**/*.ts\", \"**/*.tsx\", \"**/*.py\", \"**/*.json\", \"**/*.yaml\", \"**/*.yml\", \"**/*.toml\"]\n",
    "\n",
    "# Exclude patterns are applied after includes and in addition to .gitignore\n",
    "# and built-in dependency/vendor/build/sensitive-path skips.\n",
    "exclude = [\"**/*.test.ts\", \"**/*.spec.ts\", \"**/__tests__/**\"]\n",
    "\n",
    "# v0.1.0 uses the first configured format unless --format is passed.\n",
    "formats = [\"markdown\"]\n",
    "\n",
    "# Policy defaults keep scans advisory. Use enforce mode in CI after reviewing reports.\n",
    "mode = \"advisory\"\n",
    "fail_severity = \"high\"\n",
    "fail_categories = []\n",
    "include_finding_ids = []\n",
    "exclude_finding_ids = []\n",
    "# baseline = \"sessionscope-baseline.json\"\n",
    "\n",
    "max_file_size_bytes = 1000000\n",
    "\n",
    "# Hints are parsed for future detectors and have no runtime effect yet.\n",
    "framework_hints = [\"express\", \"nextjs\", \"fastapi\", \"django\"]\n",
    "provider_hints = []\n",
);

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectConfig {
    pub scan_paths: Option<Vec<String>>,
    pub include: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub formats: Option<Vec<String>>,
    pub mode: Option<PolicyMode>,
    pub fail_severity: Option<String>,
    pub fail_categories: Option<Vec<String>>,
    pub include_finding_ids: Option<Vec<String>>,
    pub exclude_finding_ids: Option<Vec<String>>,
    pub baseline: Option<String>,
    pub max_file_size_bytes: Option<u64>,
    pub framework_hints: Option<Vec<String>>,
    pub provider_hints: Option<Vec<String>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PolicyMode {
    Advisory,
    Enforce,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConfigError {
    Read(String),
    Parse(String),
    Validation(String),
}

impl fmt::Display for ConfigError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Read(message) | Self::Parse(message) | Self::Validation(message) => {
                formatter.write_str(message)
            }
        }
    }
}

impl Error for ConfigError {}

impl ProjectConfig {
    pub fn empty() -> Self {
        Self {
            scan_paths: None,
            include: None,
            exclude: None,
            formats: None,
            mode: None,
            fail_severity: None,
            fail_categories: None,
            include_finding_ids: None,
            exclude_finding_ids: None,
            baseline: None,
            max_file_size_bytes: None,
            framework_hints: None,
            provider_hints: None,
        }
    }

    pub fn load_default() -> Result<Self, ConfigError> {
        let path = Path::new(CONFIG_FILE_NAME);
        if path.exists() {
            Self::load_from(path)
        } else {
            Ok(Self::empty())
        }
    }

    pub fn load_from(path: &Path) -> Result<Self, ConfigError> {
        let contents = fs::read_to_string(path).map_err(|error| {
            ConfigError::Read(format!("failed to read {CONFIG_FILE_NAME}: {error}"))
        })?;
        Self::parse(&contents)
    }

    pub fn parse(contents: &str) -> Result<Self, ConfigError> {
        let config: Self = toml::from_str(contents)
            .map_err(|error| ConfigError::Parse(format_parse_error(contents, &error)))?;
        config.validate()?;
        Ok(config)
    }

    pub fn first_scan_path(&self) -> Option<&str> {
        self.scan_paths
            .as_ref()
            .and_then(|paths| paths.first().map(String::as_str))
    }

    pub fn first_format(&self) -> Result<Option<ReportFormat>, ConfigError> {
        let Some(formats) = &self.formats else {
            return Ok(None);
        };

        let Some(format) = formats.first() else {
            return Ok(None);
        };

        ReportFormat::parse(format).map(Some).map_err(|_| {
            ConfigError::Validation(format!(
                "unsupported format in {CONFIG_FILE_NAME}; expected markdown, json, sarif, or github-summary"
            ))
        })
    }

    fn validate(&self) -> Result<(), ConfigError> {
        validate_non_empty_list(self.scan_paths.as_ref(), "scan_paths")?;
        validate_non_empty_list(self.formats.as_ref(), "formats")?;
        if self.max_file_size_bytes == Some(0) {
            return Err(ConfigError::Validation(
                "max_file_size_bytes must be greater than zero".to_string(),
            ));
        }

        if let Some(formats) = &self.formats {
            for format in formats {
                ReportFormat::parse(format).map_err(|_| {
                    ConfigError::Validation(format!(
                        "unsupported format in {CONFIG_FILE_NAME}; expected markdown, json, sarif, or github-summary"
                    ))
                })?;
            }
        }

        if let Some(severity) = &self.fail_severity {
            parse_severity(severity).map_err(ConfigError::Validation)?;
        }

        if let Some(categories) = &self.fail_categories {
            for category in categories {
                parse_category(category).map_err(ConfigError::Validation)?;
            }
        }

        Ok(())
    }
}

fn format_parse_error(contents: &str, error: &toml::de::Error) -> String {
    if let Some(span) = error.span() {
        let (line, column) = line_column(contents, span.start);
        format!("invalid {CONFIG_FILE_NAME}; check TOML syntax near line {line}, column {column}")
    } else {
        format!("invalid {CONFIG_FILE_NAME}; check TOML syntax")
    }
}

fn line_column(contents: &str, byte_offset: usize) -> (usize, usize) {
    let mut line = 1;
    let mut column = 1;

    for (index, ch) in contents.char_indices() {
        if index >= byte_offset {
            break;
        }
        if ch == '\n' {
            line += 1;
            column = 1;
        } else {
            column += 1;
        }
    }

    (line, column)
}

fn validate_non_empty_list(values: Option<&Vec<String>>, field: &str) -> Result<(), ConfigError> {
    if values.is_some_and(Vec::is_empty) {
        return Err(ConfigError::Validation(format!(
            "{field} must contain at least one value"
        )));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{DEFAULT_CONFIG, PolicyMode, ProjectConfig};

    #[test]
    fn parses_generated_config() {
        let config = ProjectConfig::parse(DEFAULT_CONFIG).expect("default config should parse");

        assert_eq!(config.first_scan_path(), Some("."));
        assert_eq!(config.mode, Some(PolicyMode::Advisory));
        assert_eq!(config.fail_severity.as_deref(), Some("high"));
        assert!(
            config
                .fail_categories
                .as_ref()
                .is_some_and(|values| values.is_empty())
        );
        assert_eq!(config.max_file_size_bytes, Some(1_000_000));
        assert!(
            config
                .include
                .as_ref()
                .is_some_and(|values| !values.is_empty())
        );
        assert!(
            config
                .exclude
                .as_ref()
                .is_some_and(|values| !values.is_empty())
        );
        assert!(
            config
                .framework_hints
                .as_ref()
                .is_some_and(|values| values.iter().any(|value| value == "express"))
        );
    }

    #[test]
    fn validates_policy_modes_and_formats() {
        let advisory = ProjectConfig::parse("mode = \"advisory\"\nformats = [\"json\"]\n")
            .expect("advisory mode should parse");
        assert_eq!(advisory.mode, Some(PolicyMode::Advisory));
        assert!(
            advisory
                .first_format()
                .expect("format should validate")
                .is_some()
        );

        let enforce = ProjectConfig::parse("mode = \"enforce\"\nformats = [\"markdown\"]\n")
            .expect("enforce mode should parse");
        assert_eq!(enforce.mode, Some(PolicyMode::Enforce));

        let enforcement = ProjectConfig::parse(concat!(
            "mode = \"enforce\"\n",
            "fail_severity = \"medium\"\n",
            "fail_categories = [\"high_confidence_misconfiguration\"]\n",
            "include_finding_ids = [\"finding_one\"]\n",
            "exclude_finding_ids = [\"finding_two\"]\n",
            "baseline = \"sessionscope-baseline.json\"\n",
        ))
        .expect("enforcement config should parse");
        assert_eq!(enforcement.fail_severity.as_deref(), Some("medium"));
        assert_eq!(
            enforcement.fail_categories.as_ref().unwrap(),
            &vec!["high_confidence_misconfiguration".to_string()]
        );
        assert_eq!(
            enforcement.include_finding_ids.as_ref().unwrap(),
            &vec!["finding_one".to_string()]
        );
        assert_eq!(
            enforcement.exclude_finding_ids.as_ref().unwrap(),
            &vec!["finding_two".to_string()]
        );
        assert_eq!(
            enforcement.baseline.as_deref(),
            Some("sessionscope-baseline.json")
        );
    }

    #[test]
    fn rejects_invalid_config_values() {
        assert!(ProjectConfig::parse("mode = \"block\"\n").is_err());
        assert!(ProjectConfig::parse("scan_paths = []\n").is_err());
        assert!(ProjectConfig::parse("formats = []\n").is_err());
        assert!(ProjectConfig::parse("formats = [\"xml\"]\n").is_err());
        assert!(ProjectConfig::parse("fail_severity = \"critical\"\n").is_err());
        assert!(ProjectConfig::parse("fail_categories = [\"unknown\"]\n").is_err());
        assert!(ProjectConfig::parse("max_file_size_bytes = 0\n").is_err());
        assert!(ProjectConfig::parse("unexpected = true\n").is_err());
    }

    #[test]
    fn parse_errors_do_not_echo_config_source() {
        let error = ProjectConfig::parse("client_secret = \"super-secret-value\n")
            .expect_err("invalid TOML should fail")
            .to_string();

        assert!(error.contains("invalid sessionscope.toml"));
        assert!(error.contains("line 1"));
        assert!(!error.contains("client_secret"));
        assert!(!error.contains("super-secret-value"));
    }
}
